name: Deploy QAApp to GitHub Pages

on:
  push:
    branches:
      - main  # lub master, zależnie od Twojej gałęzi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pobranie repo
      - uses: actions/checkout@v3

      # 2️⃣ Utworzenie config.js z sekretów
      - name: Generate config.js from secrets
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
          };" > config.js

      # 3️⃣ Wylistowanie wszystkich plików (debug)
      - name: List files
        run: ls -R

      # 4️⃣ Wypchnięcie na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # katalog root repo z index.html, app.html, script.js, style.css, config.js
